name: open_con
description: OpenCon-20 Client App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.3+1
  provider: ^4.0.1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.0+1
  shared_preferences: ^0.5.6
  url_launcher: ^5.0.2
  uni_links: ^0.2.0
  http: ^0.12.0+1
  intl: ^0.16.1
  flutter_swiper: ^1.1.6
  flutter_dotenv: ^2.1.0
  permission_handler: '^4.2.0+hotfix.3'
  chirp_flutter: ^1.0.1+1
  cached_network_image: ^2.1.0+1
  flutter_dialogflow: ^0.1.3
  flutter_tts: ^1.0.0
  bubble: ^1.1.9+1
  bouncing_widget: ^1.2.0
  sliding_up_panel: ^1.0.2
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/opencon_logo.png
    - assets/google_logo.png
    - assets/frame.png
    - assets/github.png
    - assets/speaking.png
    - assets/not-speaking.png
    - assets/opencon-20-081be2339280.json
    - assets/ink-shape.png
    - assets/ink.png
    - assets/chat.png
    - assets/back.png
    - assets/faq.png
    - assets/send.png
    - .ENV

  fonts:
    - family: Blinker
      fonts:
        - asset: assets/Blinker/Blinker-Regular.ttf
        - asset: assets/Blinker/Blinker-SemiBold.ttf
        - asset: assets/Blinker/Blinker-Bold.ttf
        - asset: assets/Blinker/Blinker-Light.ttf
